name: libras4all-web

on:
  push:
    braches:
      - main
  workflow_dispatch:

jobs:
  deploy_dev:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}